### ISSUE TITLE
Issues with PyDriller

### ISSUE THREAD

**Issue by declanjcasey** [GatorCogitate/cogitate_tool#10]
We've been having some issues getting PyDriller running, we've even tried reusing example code from readthedocs but for some reason PyDriller isn't being recognized as a module to be imported, this hasn't been an issue for examples online. Some members are having trouble with the tool and how it interacts with pipenv and pyenv commands, so we are beginning to think PyDriller may be to difficult to implement, however we have been searching for other tools that do similar things such as PyGitHub. We can still show code in our presentation and talk about the different methods that PyDriller uses, we just can't run the code. Any help would be appreciated.

**Comment by declanjcasey** [comment]
Just to add, sorry for the short notice, we had one issue over the weekend we thought was simple enough to fix by lab today, and new problems have begun to pop up since yesterday

**Comment by noorbuchi** [comment]
@declanjcasey can you please paste the error message that you get when trying to rin the program.

**Comment by noorbuchi** [comment]
@declanjcasey after looking at the pipfile in your repo, I suggest moving the packages in the [packages] section to the [dev-packages] then running `pip install pipenv --user` and `pipenv install --dev` in the main directory where the pipfile is. Please let me know if that works.

**Comment by declanjcasey** [comment]
Well we're having a couple different ones depending on what we want to do, when trying to remotely clone a repo rather than import it, I get:
Traceback (most recent call last):
  File "PyDriller-Demo.py", line 8, in <module>
    for commit in RepositoryMining("code/demo").traverse_commits():
  File "/Users/dcasey/.local/share/virtualenvs/cogitate_tool-wUX9pCS3/lib/python3.7/site-packages/pydriller/repository_mining.py", line 167, in traverse_commits
    'only_in_branch'), not self._conf.get('reversed_order')):
  File "/Users/dcasey/.local/share/virtualenvs/cogitate_tool-wUX9pCS3/lib/python3.7/site-packages/pydriller/git_repository.py", line 126, in get_list_commits
    for commit in self.repo.iter_commits(branch, reverse=reverse_order):
  File "/Users/dcasey/.local/share/virtualenvs/cogitate_tool-wUX9pCS3/lib/python3.7/site-packages/pydriller/git_repository.py", line 82, in repo
    self._open_repository()
  File "/Users/dcasey/.local/share/virtualenvs/cogitate_tool-wUX9pCS3/lib/python3.7/site-packages/pydriller/git_repository.py", line 95, in _open_repository
    self._repo = Repo(str(self.path))
  File "/Users/dcasey/.local/share/virtualenvs/cogitate_tool-wUX9pCS3/lib/python3.7/site-packages/git/repo/base.py", line 130, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /Users/dcasey/Desktop/CS 203/Labs/cogitate_tool/code/code/demo

**Comment by noorbuchi** [comment]
I'm not sure what is causing this issue. Does cloning the repo on a different machine work?

**Comment by declanjcasey** [comment]
No, it hasn't worked for any of us so far

**Comment by WonjoonC** [comment]
I've had the same issue on a Windows 10 OS.

**Comment by schultzh** [comment]
Could you please us backticks when copy and pasting code/error messages? It will make it easier to read and easier for us to help solve the issue.

**Comment by declanjcasey** [comment]
We'll still be able to show what working code _should_ look like and discuss it, the functionality is just not there, maybe we can discuss more in depth in our lab session?

**Comment by WonjoonC** [comment]
```
C:\Users\Wonjoon Cho\CMPSC 203\Lab\3\cogitate_tool>python PyDriller-Demo.py
Traceback (most recent call last):
  File "PyDriller-Demo.py", line 3, in <module>
    for commit in RepositoryMining("code/demo").traverse_commits():
  File "C:\Users\Wonjoon Cho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pydriller\repository_mining.py", line 167, in traverse_commits
    'only_in_branch'), not self._conf.get('reversed_order')):
  File "C:\Users\Wonjoon Cho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pydriller\git_repository.py", line 126, in get_list_commits
    for commit in self.repo.iter_commits(branch, reverse=reverse_order):
  File "C:\Users\Wonjoon Cho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pydriller\git_repository.py", line 82, in repo
    self._open_repository()
  File "C:\Users\Wonjoon Cho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pydriller\git_repository.py", line 95, in _open_repository
    self._repo = Repo(str(self.path))
  File "C:\Users\Wonjoon Cho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\git\repo\base.py", line 130, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: C:\Users\Wonjoon Cho\CMPSC 203\Lab\3\cogitate_tool\code\demo
```

**Comment by noorbuchi** [comment]
I'll try to run the code on my end after checking out the branch. Do you just use the command `pipenv run python filename.py`?

**Comment by hinckleyc** [comment]
Yes, that is what we used.

**Comment by noorbuchi** [comment]
Thank @hinckleyc ! I managed to switch to the branch. Which file do you usually run as there are three of them?

**Comment by declanjcasey** [comment]
The code to be run for the demo is PyDriller-Demo.py

**Comment by declanjcasey** [comment]
The Repository mining program was added because the import doesn't work and can't import the class, so we tried cloning it but to no avail

**Comment by noorbuchi** [comment]
List of errors I got when running each file:

- When running `demo.py`
```
Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    with open("stopwords/stop_words.txt") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'stopwords/stop_words.txt
````

- When running `PyDriller-Demo.py`
```
Traceback (most recent call last):
  File "PyDriller-Demo.py", line 1, in <module>
    repo = Repo("code/demo")
NameError: name 'Repo' is not defined
```

- When running `RepositoryMining.py` I got no error message but I also didn't get any output

**Comment by declanjcasey** [comment]
Yeah, so the only program that is supposed to be run for the demo is PyDriller-Demo.py. The demo.py is code we were originally going to demonstrate PyDriller's methods on, and RepoitoryMining.py shouldn't have output

**Comment by declanjcasey** [comment]
Some of the code in PyDriller-Demo shouldn't be working at the moment because we made it generic for demonstration purposes after the fact. The error for PyDriller-Demo is where we are having trouble, that Repo() method should be imported from the pydriller package which is not working

**Comment by noorbuchi** [comment]
I managed to remove that error by adding `from git import Repo` at the top but I faced directory error due to the wrong directory when initiating the variable repo.

**Comment by declanjcasey** [comment]
I would pull if I were you, I think our code has changed because I don't see that variable anymore, maybe we should just talk in person, it's a bit tough to keep going back and forth

**Comment by noorbuchi** [comment]
Ok sounds good! I'm on my way to Alden
